### ISSUE TITLE
Cache-master and query monitor plugin.

### ISSUE THREAD

**Issue by baiyuanlab** [terrylinooo/cache-master#2]
Hi, Terry 
The first step is to install the cache-master, and the second step is to select the cache driver, such as redis, the third step, storage, errors will occur, please refer to the screenshot.

[https://lemp365.tw/cache-master-101/](url)
**Cache Master**
Version Core: 1.2.0 Plugin: 2.0.0

**Query Monitor**
Version 1.6.12

I look forward to your reply.

**Comment by terrylinooo** [comment]
Fixed. Thank you very much for reporting issues.

**Comment by baiyuanlab** [comment]
> Fixed. Thank you very much for reporting issues.

Thank you for the information about your current fixed.
