### ISSUE TITLE
Fatal on WP6.1/PHP8 updating Option/Exclusions

### ISSUE THREAD

**Issue by kech61** [terrylinooo/cache-master#24]
Hi,

Thanks for this great plugin.

I had an Fatal Error while updating excluded urls on WP6/PHP8:

[24-Aug-2022 07:24:04 UTC] PHP Fatal error:  Uncaught TypeError: explode(): Argument #2 ($string) must be of type string, array given in /data/web/myserver/html/oam/wp-content/plugins/cache-master/inc/admin/update-setting.php:267
Stack trace:
#0 /data/web/myserver/html/oam/wp-content/plugins/cache-master/inc/admin/update-setting.php(267): explode()
#1 /data/web/myserver/html/oam/wp-includes/class-wp-hook.php(309): scm_update_exclusion()
#2 /data/web/myserver/html/oam/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#3 /data/web/myserver/html/oam/wp-includes/plugin.php(476): WP_Hook->do_action()
#4 /data/web/myserver/html/oam/wp-includes/option.php(530): do_action()
#5 /data/web/myserver/html/oam/wp-admin/options.php(322): update_option()
#6 {main}
  thrown in /data/web/myserver/html/oam/wp-content/plugins/cache-master/inc/admin/update-setting.php on line 267

Is this plugin still maintained?
Its the only real working Plugin for Memcached......
;-)

Thanks and best regards

**Comment by terrylinooo** [comment]
I'm looking into this issue. It wil be fixed later.
