### ISSUE TITLE
Memcached and Redis: Unix socket of TCP

### ISSUE THREAD

**Issue by dreamon11** [terrylinooo/cache-master#4]
Hello,

We can only define TCP socket with Memcached and Redis with IP (‘127.0.0.1’) and port (‘11211’).

It would be great if we can define Unix socket like ‘/var/run/memcached/memcached.sock’.

Do you think you can add this option?

Thanks!

**Comment by terrylinooo** [comment]
Okay. I will add them in the next version.

**Comment by dreamon11** [comment]
Great ❤️ 
Unix socket is much faster than TCP!

**Comment by terrylinooo** [comment]
New setting options for this feature has been added to current version (2.1.0)
